In [15]:
#dependencies
import numpy as np

#input data
input_data = ([
 [0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]
])
output_data = ([[0],[1],[1],[0]])

print(input_data)
print(output_data)



[[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]]
[[0], [1], [1], [0]]


In [16]:
# sigmoid function
def activate(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [17]:
# 2 weight values
synaptic_weight_0 = 2*np.random.random((3,4)) - 1
synaptic_weight_1 = 2*np.random.random((4,1)) - 1

print(synaptic_weight_0)
print(synaptic_weight_1)

[[-0.57121616  0.34220569 -0.69246932 -0.94111218]
 [ 0.16863187 -0.39867692 -0.74650619  0.65600246]
 [ 0.70933228  0.44624326 -0.84345471  0.88945636]]
[[ 0.59819745]
 [ 0.60272113]
 [-0.99399737]
 [ 0.4890311 ]]


In [18]:
for j in range(600000):
    layer0 = input_data
    layer1 = activate(np.dot(layer0, synaptic_weight_0))
    layer2 = activate(np.dot(layer1, synaptic_weight_1))
    
    layer2_error = output_data - layer2
    if(j % 10000) == 0:
        print("Error " + str(np.mean(np.abs(layer2_error))))
    
    #compute the gradient using layer 2 error
    layer2_gradient = layer2_error*activate(layer2, deriv=True)
    
    #calculate error for layer 1
    layer1_error = layer2_gradient.dot(synaptic_weight_1.T)
    
    #use it to compute the gradient
    layer1_gradient = layer1_error * activate(layer1, deriv=True)
    
    #update weights using the gradient
    synaptic_weight_1 += layer1.T.dot(layer2_gradient)
    synaptic_weight_0 += layer2.T.dot(layer1_gradient)

Error 0.499163705414444


Error 0.4079891803280009


Error 0.3980706488817023


Error 0.39285882478944795


Error 0.3894098137039862


Error 0.38686630428612423


Error 0.3848682480673238


Error 0.3832322284286983


Error 0.3818527891483886


Error 0.38066401537515004


Error 0.3796221012075166


Error 0.3786965319246651


Error 0.3778652444970114


Error 0.3771117967053851


Error 0.37642362410485875


Error 0.3757909205664966


Error 0.3752058934477651


Error 0.37466225289948973


Error 0.3741548525249476


Error 0.37367943077181986


Error 0.3732324210962873


Error 0.37281081014445727


Error 0.3724120301345929


Error 0.37203387603702


Error 0.3716744410243179


Error 0.37133206557910625


Error 0.37100529694669426


Error 0.37069285651819095


Error 0.3703936133605785


Error 0.3701065625599098


Error 0.36983080736869584


Error 0.36956554438619904


Error 0.369310051176316


Error 0.369063675859288


Error 0.3688258283129704


Error 0.3685959726952186


Error 0.36837362105734894


Error 0.3681583278638595


Error 0.36794968526904825


Error 0.36774731902899926


Error 0.3675508849495143


Error 0.36736006578820746


Error 0.3671745685431234


Error 0.3669941220716746


Error 0.36681847499297154


Error 0.3666473938341964


Error 0.36648066138787055


Error 0.36631807525199944


Error 0.36615944652930055


Error 0.36600459866525514


Error 0.3658533664076504


Error 0.36570559487275345


Error 0.36556113870532747


Error 0.3654198613214431


Error 0.36528163422453097


Error 0.3651463363863684


Error 0.36501385368578


Error 0.3648840783987377


Error 0.3647569087343423


Error 0.36463224841184094


NameError: name 'syn0' is not defined